#$ -l u5
#$ -o /cdat/tem/mccann/id122808.log
#$ -S /bin/bash
#$ -j y

cd /home/mccann/acceptance/run3/
. /nfs/cleo3/scripts/cleo3defs
c3rel cleo3_Pass2_Mar26_2002

export USER_DB=17
export USER_RUN=122808
export USER_EA=false
export USER_REL=cleo3_Pass2_Mar26_2002

rm -f ../rzn3/raw$USER_RUN.pds
suez -f run_index.tcl
rm -f core

c3rel Dec10_03

suez -f trigger_only.tcl
rm -f core

suez -f ntuple.tcl
rm -f core
