file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121916_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121917_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121918_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121920_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121924_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121925_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121927_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121928_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121929_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121930_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121932_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121933_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121936_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121939_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121940_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121943_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121944_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121946_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121948_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121949_db16.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y3ggg_121950_db16.pds physics event startrun beginrun endrun
