file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129535_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129536_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129538_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129539_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129540_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129541_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129545_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129549_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129550_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129551_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129552_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129553_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129564_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129566_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129567_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129568_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129572_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129573_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129574_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129575_db23.pds physics event startrun beginrun endrun
file add pdschain /home/mccann/mcsuper/pds/mcpass2_y2ggg_129576_db23.pds physics event startrun beginrun endrun
